export const SET_BASIC_INFO = 'SET_BASIC_INFO'
export const SET_MEMBER_INFO = 'SET_MEMBER_INFO'

export const USER_SIGNIN = 'USER_SIGNIN'
export const USER_SIGNOUT = 'USER_SIGNOUT'
export const CHANGE_USER_INFO = 'CHANGE_USER_INFO'

export const CLEAR_NEW_ROOM = 'CLEAR_NEW_ROOM'

export const GET_ROOMS = 'GET_ROOMS'
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE'
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE'

export const GET_MESSAGES = 'GET_MESSAGES'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const CREATE_MESSAGE = 'CREATE_MESSAGE'

export const GET_MEMBERS = 'GET_MEMBERS'
export const DELETE_MEMBER = 'DELETE_MEMBER'
export const GET_ROOM_INFO = 'GET_ROOM_INFO'
export const GET_MEMBER_INFO = 'GET_MEMBER_INFO'
export const GET_APPLICATIONS = 'GET_APPLICATIONS'
export const ACCEPT_APPLICATION = 'ACCEPT_APPLICATION'

export const SEARCH_ROOMS_BY_NAME = 'SEARCH_ROOMS_BY_NAME'
export const SEARCH_ROOMS_BY_LABELS = 'SEARCH_ROOMS_BY_LABELS'
