export const SET_BASIC_INFO = 'SET_BASIC_INFO'
export const SET_MEMBER_INFO = 'SET_MEMBER_INFO'

export const USER_SIGNIN = 'USER_SIGNIN'
export const USER_SIGNOUT = 'USER_SIGNOUT'

export const GET_ROOMS = 'GET_ROOMS'
export const CLEAR_BASIC_INFO = 'CLEAR_BASIC_INFO'
export const CLEAR_MEMBER_INFO = 'CLEAR_MEMBER_INFO'
