export const SET_BASIC_INFO = 'SET_BASIC_INFO'
export const SET_MEMBER_INFO = 'SET_MEMBER_INFO'

export const USER_SIGNIN = 'USER_SIGNIN'
export const USER_SIGNOUT = 'USER_SIGNOUT'

export const CLEAR_NEW_ROOM = 'CLEAR_NEW_ROOM'

export const GET_ROOMS = 'GET_ROOMS'
export const CHANGE_LOADING = 'CHANGE_LOADING'

export const GET_MESSAGES = 'GET_MESSAGES'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const CREATE_MESSAGE = 'CREATE_MESSAGE'

export const GET_MEMBERS = 'GET_MEMBERS'
export const GET_ROOM_INFO = 'GET_ROOM_INFO'
export const GET_APPLICATIONS = 'GET_APPLICATIONS'
